apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - speedtest.domain.com
    secretName: speedtest-tls
  rules:
  - host: speedtest.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: speedtest-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-service
spec:
  selector:
    app: speedtest-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speedtest-pod
  template:
    metadata:
      labels:
        app: speedtest-pod
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: speedtest-pod
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: speedtest
        image: openspeedtest/latest
        ports:
        - name: http
          containerPort: 3000
        - name: https
          containerPort: 3001
