apiVersion: v1
kind: Service
metadata:
  name: service-externalips
spec:
  selector:
    app: my-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 1.2.3.4
