apiVersion: v1
kind: Service
metadata:
  name: service-headless
spec:
  clusterIP: None
  selector:
    app: my-app
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: 9376
