apiVersion: v1
kind: Pod
metadata:
  name: pod-nfs
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /nfs/test-webserver
      name: nfs-volume
  volumes:
  - name: nfs-volume
    nfs:
      server: nfs.server.com
      path: /nfs
      readOnly: false
